import Head from 'next/head'
import { useFormik } from 'formik'
import * as Yup from 'yup'  // form validation

export default function Home() {

  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'India',
      terms: '',
    },
    
    //Validate form
    validationSchema: Yup.object({
      name: Yup.string().max(20, 'Name must be under 20 characters or less').required('Name is required'),
      email: Yup.string().email('Invalid email address').required('Email is required'),
      terms: Yup.array().email().required('Terms of service must be checked'),
    }),

    //Submit form
    onSubmit: (values) => {
      console.log(formik.values)
    },
  })

  console.log(formik.values)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex items-center justify-center '>
        <form className='bg-white flex rounded-lg w-1/2 shadow-lg shadow-gray-300 '>
          <div className='flex-1 text-gray-700 p-20'>
            <h1 className='text-3xl pb-3 font-bold'> 
              Let's get started 👋
            </h1>
            <p className='text-lg text-gray-500'>
              Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.
            </p>
            <div className='mt-6'>
            <div className='pb-4'>
                <label className='block text-sm pb-2'>Name </label>
                <input type='text' placeholder='Enter your name' name='name' className='border-2 border-gray-500 rounded-md p-2 w-1/2' value={formik.values.name} onChange={formik.handleChange}></input>
            </div>
            <div className='pb-4'>
                <label className='block text-sm pb-2'>Email </label>
                <input type='email' placeholder='Enter your email' name='email' className='border-2 border-gray-500 rounded-md p-2 w-1/2' value={formik.values.email} onChange={formik.handleChange}></input>
            </div>
            <div className='pb-4'>
                <label className='block text-sm pb-2'>Country </label>
                <select name='country' className='border-2 border-gray-500 rounded-md p-2 w-1/2' value={formik.values.country} onChange={formik.handleChange}>
                  <option>India</option>
                  <option>Some other country</option>
                </select>
            </div>

            <div className='pb-4'>
                <label className='block text-sm pb-2'>Terms of service </label>
                <div className='flex items-center gap-2'>
                  <input type='checkbox' name='terms' className='h-5 w-5 text-[#3AACD9] border-2' value='checked' onChange={formik.handleChange}></input>
                  <p>I agree to the Terms and Service that my data will be taken and sold... 😂</p>
                </div>
            </div>

            <button className='bg-[#3AACD9] bold text-sm text-white mt-6 py-3 rounded-lg w-full' type='submit'>Start Learning Today!!</button>
            
            </div>
          </div>
        </form>
      </main>
    </div>
  )
}
