import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex items-center justify-center '>
        <form className='bg-white flex rounded-lg w-1/2 '>
          <div className=''>
            <h1>Lets get started</h1>
            <p>Join our e learning platform today and unlock over ....... </p>
          </div>
          <div>

          </div>
        </form>
      </main>
    </div>
  )
}
